version: 2
workflows:
  version: 2
  test:
    jobs:
      - enable-ipv6
      # - ruby-2.1
      # - ruby-2.2
      # - ruby-2.3
      # - ruby-2.4
      - ruby-2.5:
          requires:
            - enable-ipv6
      # - ruby-rbx-3
      # - ruby-jruby
      # - ruby-ruby-head
jobs:
  enable-ipv6:
    machine: true
    steps:
    - run:
        name: enable ipv6
        command: |
          cat <<'EOF' | sudo tee /etc/docker/daemon.json
          {
            "ipv6": true,
            "fixed-cidr-v6": "2001:db8:1::/64"
          }
          EOF
          sudo service docker restart
  ruby-2.5: &test-template
    docker:
      - image: circleci/ruby:2.5
        environment: # environment variables for primary container
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      # Install Ruby dependencies
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake spec
